name: Tests

on:
    push: 
        branches:
            master
    pull_request: {}
    schedule:
        - cron: '0 1 * * 1'

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                phpstan: [ '^1.0', '^2.0' ]
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer
            - run: composer require "phpstan/phpstan:${{ matrix.phpstan }}"
            - run: composer test

    format:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1' ]
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer
            - run: composer install
            - run: composer format

    analyse:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1' ]
                phpstan: [ '^1.0', '^2.0' ]
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP with tools
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer
            - run: composer require "phpstan/phpstan:${{ matrix.phpstan }}"
            - run: composer analyse
